name: Deploy React app

on:
    push:
        branches:
            - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use the Node.js version that matches your project

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    - name: Upload production-ready package
      uses: actions/upload-artifact@v3
      with:
        name: react-app-build
        path: build  # This is the build folder created by `npm run build`